import { fileURLToPath, URL } from 'node:url';
import { readFileSync } from 'node:fs';
import { defineConfig, type Plugin } from 'vitest/config';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import { VitePWA } from 'vite-plugin-pwa';
import {
  SPLASH_DEVICES,
  SPLASH_THEMES,
  splashFileName,
  splashMedia,
} from './scripts/splashScreens.ts';

const BASE = '/Manager/';

const pkg = JSON.parse(readFileSync(new URL('./package.json', import.meta.url), 'utf8')) as {
  version: string;
};

/** Background of the dark theme (= --bg in src/styles/tokens.css). */
const THEME_COLOR = '#090D16';

/**
 * Content-Security-Policy as meta tag. Only added to production builds, because the
 * Vite dev server relies on inline scripts/styles for HMR. Extend deliberately, each with the
 * step that needs it: api.anthropic.com (optional AI) since step 3; YouTube Data and
 * Analytics API since step 9 (sign-in is a navigation to accounts.google.com, no connect-src);
 * Meta (Instagram) in step 10.
 */
const CSP = [
  "default-src 'self'",
  "script-src 'self'",
  "style-src 'self'",
  "img-src 'self' data: blob:",
  "font-src 'self'",
  "connect-src 'self' https://api.anthropic.com https://www.googleapis.com https://youtubeanalytics.googleapis.com",
  "worker-src 'self'",
  "manifest-src 'self'",
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self'",
].join('; ');

function cspPlugin(): Plugin {
  return {
    name: 'manager-csp',
    apply: 'build',
    transformIndexHtml: {
      order: 'post',
      handler: () => [
        {
          tag: 'meta',
          attrs: { 'http-equiv': 'Content-Security-Policy', content: CSP },
          injectTo: 'head-prepend',
        },
      ],
    },
  };
}

/** iOS startup images (generated by npm run icons) as apple-touch-startup-image links. */
function splashPlugin(): Plugin {
  return {
    name: 'manager-splash',
    transformIndexHtml: () =>
      SPLASH_DEVICES.flatMap((device) =>
        (['portrait', 'landscape'] as const).flatMap((orientation) =>
          SPLASH_THEMES.map((theme) => ({
            tag: 'link',
            attrs: {
              rel: 'apple-touch-startup-image',
              media: splashMedia(device, orientation, theme),
              href: `${BASE}splash/${splashFileName(device, orientation, theme)}`,
            },
            injectTo: 'head' as const,
          })),
        ),
      ),
  };
}

export default defineConfig({
  base: BASE,
  define: {
    __APP_VERSION__: JSON.stringify(pkg.version),
    __BUILD_TIME__: JSON.stringify(new Date().toISOString()),
  },
  resolve: {
    alias: [{ find: '@', replacement: fileURLToPath(new URL('./src', import.meta.url)) }],
  },
  plugins: [
    react(),
    tailwindcss(),
    cspPlugin(),
    splashPlugin(),
    VitePWA({
      registerType: 'prompt',
      injectRegister: false,
      includeAssets: ['icons/favicon.svg', 'icons/apple-touch-icon-180x180.png'],
      manifest: {
        id: BASE,
        name: 'Manager',
        short_name: 'Manager',
        description: 'Deine persönliche Schaltzentrale.',
        lang: 'de',
        start_url: BASE,
        scope: BASE,
        display: 'standalone',
        orientation: 'any',
        background_color: THEME_COLOR,
        theme_color: THEME_COLOR,
        icons: [
          { src: 'icons/pwa-192x192.png', sizes: '192x192', type: 'image/png' },
          { src: 'icons/pwa-512x512.png', sizes: '512x512', type: 'image/png' },
          {
            src: 'icons/maskable-icon-512x512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
      workbox: {
        // Own cache names: Kompass and Synapse run on the same origin (GitHub Pages).
        cacheId: 'manager',
        globPatterns: ['**/*.{js,css,html,svg,png,woff2,webmanifest}'],
        // iOS loads the startup images itself when the app is added to the home screen.
        globIgnores: ['splash/**'],
        navigateFallback: `${BASE}index.html`,
        cleanupOutdatedCaches: true,
      },
    }),
  ],
  build: {
    rolldownOptions: {
      output: {
        // Vendor chunks: smaller files and better caching across app updates.
        codeSplitting: {
          groups: [
            {
              name: 'react',
              test: /node_modules[\\/](react|react-dom|scheduler|react-router)[\\/]/,
            },
            {
              name: 'motion',
              test: /node_modules[\\/](motion|framer-motion|motion-dom|motion-utils)[\\/]/,
            },
            {
              name: 'data',
              // src/zodConfig.ts belongs to zod's chunk: shared app chunks create schemas
              // while they load, before the entry chunk's own code runs.
              test: /node_modules[\\/](dexie|zod)[\\/]|src[\\/]zodConfig\.ts$/,
            },
          ],
        },
      },
    },
  },
  preview: {
    port: 4173,
    strictPort: true,
  },
  test: {
    include: ['src/**/*.test.ts', 'src/**/*.test.tsx'],
    environment: 'node',
    // In-memory IndexedDB for repository tests.
    setupFiles: ['fake-indexeddb/auto'],
  },
});
